# Config
title: Danny van Kooten
email: hi@dvk.co
description:
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: dannyvankooten
github_username:  dannyvankooten

# SEO settings
twitter:
  username: dannyvankooten
  card: summary
  
social:
  name: Danny van Kooten
  links:
    - https://github.com/dannyvankooten

sass:
    style: compressed

# Build settings
markdown: kramdown

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

permalink: /:title/

exclude:
  - package.json
  - node_modules
  - gulpfile.js
  - assets/sass
  - Gemfile
  - Gemfile.lock
  - makefile
  - scripts