<?php

defined('ABSPATH') or exit;

$redirects = [
    "/atom.xml" => "/feed/",
    "/about-me/" => "/about/",
    "/100-000-plugin-downloads-6-months-mailchimp-wordpress/" => "/blog/100-000-plugin-downloads-6-months-mailchimp-wordpress/",
    "/2014-year-in-review/" => "/blog/2014-year-in-review/",
    "/2016-year-in-review/" => "/blog/2016-year-in-review/",
    "/a-new-site-built-on-ghost/" => "/blog/a-new-site-built-on-ghost/",
    "/add-mailchimp-sign-up-form-end-of-posts/" => "/blog/add-mailchimp-sign-up-form-end-of-posts/",
    "/add-plain-html-social-sharing-links-posts/" => "/blog/add-plain-html-social-sharing-links-posts/",
    "/altorouter-php-routing-class/" => "/blog/altorouter-php-routing-class/",
    "/backtesting-12-month-sma-investing-strategy-pandas/" => "/blog/backtesting-12-month-sma-investing-strategy-pandas/",
    "/browserpass-for-firefox/" => "/blog/browserpass-for-firefox/",
    "/celebrating-2-million-downloads-for-mc4wp/" => "/blog/celebrating-2-million-downloads-for-mc4wp/",
    "/chrome-extension-for-pass/" => "/blog/chrome-extension-for-pass/",
    "/codeigniter-sessions-in-ie7/" => "/blog/codeigniter-sessions-in-ie7/",
    "/configuring-newsletter-sign-up-the-definitive-guide/" => "/blog/configuring-newsletter-sign-up-the-definitive-guide/",
    "/data-type-inconsistencies-in-wordpress/" => "/blog/data-type-inconsistencies-in-wordpress/",
    "/delay-scroll-handlers-javascript/" => "/blog/delay-scroll-handlers-javascript/",
    "/dynamic-custom-menus-wordpress/" => "/blog/dynamic-custom-menus-wordpress/",
    "/enabling-shortcodes-in-widgets-quick-wordpress-tip/" => "/blog/enabling-shortcodes-in-widgets-quick-wordpress-tip/",
    "/from-go-back-to-php-again/" => "/blog/from-go-back-to-php-again/",
    "/goals-for-2013/" => "/blog/goals-for-2013/",
    "/goals-for-2020/" => "/blog/goals-for-2020/",
    "/html-forms-wordpress/" => "/blog/html-forms-wordpress/",
    "/ie-fix-for-html-5-elements/" => "/blog/ie-fix-for-html-5-elements/",
    "/interview-on-nomadlist/" => "/blog/interview-on-nomadlist/",
    "/interview-on-webworktravel/" => "/blog/interview-on-webworktravel/",
    "/introducing-ibericode/" => "/blog/introducing-ibericode/",
    "/introducing-koko-analytics/" => "/blog/introducing-koko-analytics/",
    "/join-mastodon/" => "/blog/join-mastodon/",
    "/laravel-to-golang/" => "/blog/laravel-to-golang/",
    "/mailchimp-newsletter-checkbox-contact-form-7/" => "/blog/mailchimp-newsletter-checkbox-contact-form-7/",
    "/multiple-form-themes-in-mailchimp-for-wordpress-pro/" => "/blog/multiple-form-themes-in-mailchimp-for-wordpress-pro/",
    "/my-newest-wordpress-plugin-mailchimp-for-wp/" => "/blog/my-newest-wordpress-plugin-mailchimp-for-wp/",
    "/one-million-downloads-mailchimp-wordpress/" => "/blog/one-million-downloads-mailchimp-wordpress/",
    "/only-load-contact-form-7-scripts-when-needed/" => "/blog/only-load-contact-form-7-scripts-when-needed/",
    "/periodically-check-wp-core-file-modifications/" => "/blog/periodically-check-wp-core-file-modifications/",
    "/php-routing-class-with-rest-routes/" => "/blog/php-routing-class-with-rest-routes/",
    "/reviving-ana-as-fathom/" => "/blog/reviving-ana-as-fathom/",
    "/show-mailchimp-sign-up-checkbox-in-checkout-forms/" => "/blog/show-mailchimp-sign-up-checkbox-in-checkout-forms/",
    "/solving-advent-of-code-2020-under-1-second/" => "/blog/solving-advent-of-code-2020-under-1-second/",
    "/stepping-down-fathom-maintainer/" => "/blog/stepping-down-fathom-maintainer/",
    "/using-a-cdn-with-wordpress/" => "/blog/using-a-cdn-with-wordpress/",
    "/vatmoss-in-practice/" => "/blog/vatmoss-in-practice/",
    "/version-2-of-mailchimp-for-wordpress/" => "/blog/version-2-of-mailchimp-for-wordpress/",
    "/website-carbon-emissions/" => "/blog/website-carbon-emissions/",
    "/wordpress-plugin-structure-dont-load-unnecessary-code/" => "/blog/wordpress-plugin-structure-dont-load-unnecessary-code/",
    "/writing-an-interpreter-compiler/" => "/blog/writing-an-interpreter-compiler/",
    "/blog/ie-fix-for-html-5-elements/" => "/blog/2010/ie-fix-for-html-5-elements/",
    "/blog/codeigniter-sessions-in-ie7/" => "/blog/2011/codeigniter-sessions-in-ie7/",
    "/blog/configuring-newsletter-sign-up-the-definitive-guide/" => "/blog/2011/configuring-newsletter-sign-up-the-definitive-guide/",
    "/blog/dynamic-custom-menus-wordpress/" => "/blog/2011/dynamic-custom-menus-wordpress/",
    "/blog/enabling-shortcodes-in-widgets-quick-wordpress-tip/" => "/blog/2011/enabling-shortcodes-in-widgets-quick-wordpress-tip/",
    "/blog/php-routing-class-with-rest-routes/" => "/blog/2011/php-routing-class-with-rest-routes/",
    "/blog/altorouter-php-routing-class/" => "/blog/2012/altorouter-php-routing-class/",
    "/blog/100-000-plugin-downloads-6-months-mailchimp-wordpress/" => "/blog/2013/100-000-plugin-downloads-6-months-mailchimp-wordpress/",
    "/blog/add-mailchimp-sign-up-form-end-of-posts/" => "/blog/2013/add-mailchimp-sign-up-form-end-of-posts/",
    "/blog/add-plain-html-social-sharing-links-posts/" => "/blog/2013/add-plain-html-social-sharing-links-posts/",
    "/blog/delay-scroll-handlers-javascript/" => "/blog/2013/delay-scroll-handlers-javascript/",
    "/blog/goals-for-2013/" => "/blog/2013/goals-for-2013/",
    "/blog/mailchimp-newsletter-checkbox-contact-form-7/" => "/blog/2013/mailchimp-newsletter-checkbox-contact-form-7/",
    "/blog/my-newest-wordpress-plugin-mailchimp-for-wp/" => "/blog/2013/my-newest-wordpress-plugin-mailchimp-for-wp/",
    "/blog/only-load-contact-form-7-scripts-when-needed/" => "/blog/2013/only-load-contact-form-7-scripts-when-needed/",
    "/blog/show-mailchimp-sign-up-checkbox-in-checkout-forms/" => "/blog/2013/show-mailchimp-sign-up-checkbox-in-checkout-forms/",
    "/blog/wordpress-plugin-structure-dont-load-unnecessary-code/" => "/blog/2013/wordpress-plugin-structure-dont-load-unnecessary-code/",
    "/blog/2014-year-in-review/" => "/blog/2014/2014-year-in-review/",
    "/blog/a-new-site-built-on-ghost/" => "/blog/2014/a-new-site-built-on-ghost/",
    "/blog/data-type-inconsistencies-in-wordpress/" => "/blog/2014/data-type-inconsistencies-in-wordpress/",
    "/blog/multiple-form-themes-in-mailchimp-for-wordpress-pro/" => "/blog/2014/multiple-form-themes-in-mailchimp-for-wordpress-pro/",
    "/blog/periodically-check-wp-core-file-modifications/" => "/blog/2014/periodically-check-wp-core-file-modifications/",
    "/blog/version-2-of-mailchimp-for-wordpress/" => "/blog/2014/version-2-of-mailchimp-for-wordpress/",
    "/blog/celebrating-2-million-downloads-for-mc4wp/" => "/blog/2015/celebrating-2-million-downloads-for-mc4wp/",
    "/blog/interview-on-nomadlist/" => "/blog/2015/interview-on-nomadlist/",
    "/blog/interview-on-webworktravel/" => "/blog/2015/interview-on-webworktravel/",
    "/blog/introducing-ibericode/" => "/blog/2015/introducing-ibericode/",
    "/blog/one-million-downloads-mailchimp-wordpress/" => "/blog/2015/one-million-downloads-mailchimp-wordpress/",
    "/blog/using-a-cdn-with-wordpress/" => "/blog/2015/using-a-cdn-with-wordpress/",
    "/blog/browserpass-for-firefox/" => "/blog/2016/browserpass-for-firefox/",
    "/blog/chrome-extension-for-pass/" => "/blog/2016/chrome-extension-for-pass/",
    "/blog/2016-year-in-review/" => "/blog/2017/2016-year-in-review/",
    "/blog/html-forms-wordpress/" => "/blog/2017/html-forms-wordpress/",
    "/blog/laravel-to-golang/" => "/blog/2017/laravel-to-golang/",
    "/blog/vatmoss-in-practice/" => "/blog/2017/vatmoss-in-practice/",
    "/blog/backtesting-12-month-sma-investing-strategy-pandas/" => "/blog/2018/backtesting-12-month-sma-investing-strategy-pandas/",
    "/blog/join-mastodon/" => "/blog/2018/join-mastodon/",
    "/blog/reviving-ana-as-fathom/" => "/blog/2018/reviving-ana-as-fathom/",
    "/blog/from-go-back-to-php-again/" => "/blog/2019/from-go-back-to-php-again/",
    "/blog/goals-for-2020/" => "/blog/2019/goals-for-2020/",
    "/blog/introducing-koko-analytics/" => "/blog/2019/introducing-koko-analytics/",
    "/blog/stepping-down-fathom-maintainer/" => "/blog/2019/stepping-down-fathom-maintainer/",
    "/blog/website-carbon-emissions/" => "/blog/2020/website-carbon-emissions/",
    "/blog/writing-an-interpreter-compiler/" => "/blog/2020/writing-an-interpreter-compiler/",
    "/blog/solving-advent-of-code-2020-under-1-second/" => "/blog/2021/solving-advent-of-code-2020-under-1-second/",
    "/blog/2022-12-rewriting-interpreter-rust/" => "/blog/2022/rewriting-interpreter-rust/",
    "/feed.xml" => "/feed/",
    "/sitemap-index.xml" => "/sitemap_index.xml",
    "/blog/" => "/",
    "/code/" => "/projects/",
    "/llms-full.txt" => "/llms.txt",
    "/mailchimp-for-wordpress/" => "https://www.mc4wp.com/",
];

add_action('init', function() use ($redirects) {
    $request_uri = trim($_SERVER['REQUEST_URI'] ?? '');

    if (isset($redirects[$request_uri])) {
        wp_redirect($redirects[$request_uri], 301);
        exit;
    }
});
